name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
permissions:
  contents: read
jobs:
  terraform_ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/checkout@v3
      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        